[build]
  base    = "https://github.com/prakshh/mern-ecommerce-app/tree/master/eCom-fullstack/client"
  publish = "https://github.com/prakshh/mern-ecommerce-app/tree/master/eCom-fullstack/client/build/"
  command = "yarn run build"
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200